# Generated by Django 2.1.5 on 2019-02-17 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='report date')),
                ('time', models.TimeField(verbose_name='time')),
                ('conditions', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('wave_quality', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='session date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('notes', models.CharField(max_length=200)),
                ('waves_caught', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ideal_tide', models.CharField(max_length=200)),
                ('ideal_wind', models.CharField(max_length=200)),
                ('ideal_swell_dir', models.IntegerField(default=0)),
                ('ideal_swell_height', models.IntegerField(default=0)),
                ('ideal_swell_period', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wave_Data',
            fields=[
                ('wave_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='time')),
                ('tide', models.CharField(max_length=200)),
                ('crowd', models.CharField(max_length=200)),
                ('wind_dir', models.CharField(max_length=200)),
                ('wave_height', models.IntegerField(default=0)),
                ('wave_period', models.CharField(max_length=200)),
                ('wind_speed', models.CharField(max_length=200)),
                ('conditions', models.CharField(max_length=200)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.Spot')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.Spot'),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='wave_data_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.Wave_Data'),
        ),
        migrations.AddField(
            model_name='report',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.Spot'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='homespot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.Spot'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
