# Generated by Django 2.1.5 on 2019-04-21 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20190420_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wave_data',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
    ]
