# Generated by Django 2.1.5 on 2019-04-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20190421_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='referencing_object',
            field=models.TextField(null=True),
        ),
    ]
